User/api/urls.py
from django.conf.urls import url

from User.api.views import UserCreateApiView, UserListApiView, UserDetailApiView, UserBasketApiView, BasketApiView, \
    BasketUpdateApiView, FileUploadView

urlpatterns = [
    url(r'^$', UserListApiView.as_view(), name='UserListApi'),
    url(r'^register/$', UserCreateApiView.as_view(), name='create-user'),
    url(r'^detail/(?P<pk>\w+)/$', UserDetailApiView.as_view(), name='user-detail'),
    url(r'^basket/$', BasketApiView.as_view(), name='UserBasketApi'),
    url(r'^basket/(?P<pk>\w+)/update', BasketUpdateApiView.as_view(), name='basket-update'),
    url(r'^upload/(?P<filename>[^/]+)$', FileUploadView.as_view())
]

User/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

import product
from . import views
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import password_reset
from django.contrib.auth.views import password_reset_done
from django.contrib.auth.views import password_reset_confirm
from django.contrib.auth.views import password_reset_complete

from product import views as PV

app_name = 'user'
urlpatterns = [
    url(r'^$', PV.Home.as_view()),
    url(r'^upload-file/$', TemplateView.as_view(template_name= 'User/upload.html')),

    # Allows to render our own login page
    url(r'^login/$', login, {'template_name': 'User/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'User/logout.html'}),
    url(r'register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', password_reset, {'template_name': 'User/reset_password.html',
                                               'post_reset_redirect': 'user:password_reset_done',
                                               'email_template_name': 'User/reset_password_email.html'},
        name='reset_password'),
    url(r'^rezome/$', TemplateView.as_view(template_name='User/rezome.html'), name='rules'),

    url(r'^reset-password-done$', password_reset_done, {'template_name': 'User/reset_password_done.html'},
        name='password_reset_done'),
    # url(r'^reset-password/confirm$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'User/reset_password_confirm.html',
         'post_reset_redirect': 'user:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^reset-password/complete$', password_reset_complete,
        {'template_name': 'User/reset_password_complete.html'}, name='password_reset_complete'),

]

# url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
#     name='password_reset_confirm')

# python -m smtpd -n -c DebuggingServer localhost:1025
# and adjust your mail settings accordingly:
# EMAIL_HOST = 'localhost'
# EMAIL_PORT = 1025

product/urls.py
from django.conf.urls import url, include
from .views import Home, change_items,set_timezone
from .views import detail, category

# namespace
app_name = 'product'

urlpatterns = [

    url(r'^$', Home.as_view(), name='home'),
    url(r'^product/(?P<operation>.+)/(?P<pk>\d+)/$', change_items, name='change_item'),
    url(r'^detail/(?P<pk>\d+)/$', detail, name='detail'),
    url(r'^product/(?P<product_category>.+)/$', category, name='category'),

]

shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import refresh_jwt_token
from rest_framework_jwt.views import verify_jwt_token
from product.views import contact, about_us, advertising, set_timezone,Search
from shop import settings

urlpatterns = [

    url(r'^admin/', admin.site.urls),

    url(r'', include('product.urls')),
    url(r'^user/', include('User.urls')),
   # url(r'^search/', include('haystack.urls')),
    url(r'^search/', Search,name='search'),

    url(r'^contact/$', contact, name='Contact'),
    url(r'^about-us/$', about_us, name='about-us'),
    url(r'^advertising/$', advertising, name='advertising'),
    url(r'^timezone/$', set_timezone, name='timezone'),
    url(r'^api/posts/', include('product.api.urls', namespace='api-posts')),
    url(r'^api/users/', include('User.api.urls', namespace='api-users')),

    url(r'^auth-jwt/', obtain_jwt_token),
    url(r'^auth-jwt-refresh/', refresh_jwt_token),
    url(r'^auth-jwt-verify/', verify_jwt_token),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
]

User/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User

from django.db import models


class UserProfile(models.Model):
    # Each user-field in UserProfile can only have one user
    user = models.ForeignKey(User, related_name="userprofile", null=True)
    phone_number = models.CharField(max_length=11, blank=True)

    city = models.CharField(max_length=100, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    pro_img = models.FileField(null=True, blank=True, upload_to='uploaded')

    def __str__(self):
        if self.user:
            return self.user.username
        return "unknown"

    @classmethod
    def create_profile(cls, user, phone_number):
        userprofile = cls.objects.create(

            user=user
        )
        userprofile.phone_number = phone_number
        userprofile.save()


"""
Note: Receiver of UsersMessage and GuestMessage is admin  cuz we don't need chat between users in a shop 

"""


# Here is Contact for Guest that i said before
class UsersMessage(models.Model):
    author = models.OneToOneField(User, related_name="author", null=True, blank=True)

    cooperate = 'co'
    problem_buying = 'pb'
    ask_game = 'ag'
    others = 'o'

    options = ((cooperate, 'همکاری'), (problem_buying, 'مشکل در خرید'), (ask_game, 'درخواست بازی'), (others, 'موارد دیگر'))
    issue_options = models.CharField(choices=options, default=cooperate, max_length=2)
    message = models.TextField(max_length=250, null=True)

    def __str__(self):
        return str(self.author) + " " + str(self.issue_options)


# Here is Contact for Guest that i said before
class GuestMessage(models.Model):
    Guest_first_name = models.CharField(max_length=10, null=True)
    Guest_last_name = models.CharField(max_length=10, null=True)
    Guest_email = models.EmailField(max_length=50, null=True)
    cooperate = 'co'
    problem_buying = 'pb'
    ask_game = 'ag'
    others = 'o'

    options = (
        (cooperate, 'همکاری'), (problem_buying, 'مشکل در خرید'), (ask_game, 'درخواست بازی'), (others, 'موارد دیگر'))
    issue_options = models.CharField(choices=options, default=cooperate, max_length=2)
    message = models.TextField(max_length=250, null=True)

    def __str__(self):
        return str(self.Guest_first_name) + " " + str(self.issue_options)

django_comments/forms.py
import time

from django import forms
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.forms.utils import ErrorDict
from django.utils.crypto import salted_hmac, constant_time_compare
from django.utils.encoding import force_text
from django.utils.text import get_text_list
from django.utils import timezone
from django.utils.translation import pgettext_lazy, ungettext, ugettext, ugettext_lazy as _

from . import get_model

COMMENT_MAX_LENGTH = getattr(settings, 'COMMENT_MAX_LENGTH', 3000)
DEFAULT_COMMENTS_TIMEOUT = getattr(settings, 'COMMENTS_TIMEOUT', (2 * 60 * 60))  # 2h


class CommentSecurityForm(forms.Form):
    """
    Handles the security aspects (anti-spoofing) for comment forms.
    """
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_pk = forms.CharField(widget=forms.HiddenInput)
    timestamp = forms.IntegerField(widget=forms.HiddenInput)
    security_hash = forms.CharField(min_length=40, max_length=40, widget=forms.HiddenInput)

    def __init__(self, target_object, data=None, initial=None, **kwargs):
        self.target_object = target_object
        if initial is None:
            initial = {}
        initial.update(self.generate_security_data())
        super(CommentSecurityForm, self).__init__(data=data, initial=initial, **kwargs)

    def security_errors(self):
        """Return just those errors associated with security"""
        errors = ErrorDict()
        for f in ["honeypot", "timestamp", "security_hash"]:
            if f in self.errors:
                errors[f] = self.errors[f]
        return errors

    def clean_security_hash(self):
        """Check the security hash."""
        security_hash_dict = {
            'content_type': self.data.get("content_type", ""),
            'object_pk': self.data.get("object_pk", ""),
            'timestamp': self.data.get("timestamp", ""),
        }
        expected_hash = self.generate_security_hash(**security_hash_dict)
        actual_hash = self.cleaned_data["security_hash"]
        if not constant_time_compare(expected_hash, actual_hash):
            raise forms.ValidationError("Security hash check failed.")
        return actual_hash

    def clean_timestamp(self):
        """Make sure the timestamp isn't too far (default is > 2 hours) in the past."""
        ts = self.cleaned_data["timestamp"]
        if time.time() - ts > DEFAULT_COMMENTS_TIMEOUT:
            raise forms.ValidationError("Timestamp check failed")
        return ts

    def generate_security_data(self):
        """Generate a dict of security data for "initial" data."""
        timestamp = int(time.time())
        security_dict = {
            'content_type': str(self.target_object._meta),
            'object_pk': str(self.target_object._get_pk_val()),
            'timestamp': str(timestamp),
            'security_hash': self.initial_security_hash(timestamp),
        }
        return security_dict

    def initial_security_hash(self, timestamp):
        """
        Generate the initial security hash from self.content_object
        and a (unix) timestamp.
        """

        initial_security_dict = {
            'content_type': str(self.target_object._meta),
            'object_pk': str(self.target_object._get_pk_val()),
            'timestamp': str(timestamp),
        }
        return self.generate_security_hash(**initial_security_dict)

    def generate_security_hash(self, content_type, object_pk, timestamp):
        """
        Generate a HMAC security hash from the provided info.
        """
        info = (content_type, object_pk, timestamp)
        key_salt = "django.contrib.forms.CommentSecurityForm"
        value = "-".join(info)
        return salted_hmac(key_salt, value).hexdigest()


class CommentDetailsForm(CommentSecurityForm):
    """
    Handles the specific details of the comment (name, comment, etc.).
    """
    name = forms.CharField(label=pgettext_lazy("Person name", "Name"), max_length=50)
    email = forms.EmailField(label=_("Email address"))
    url = forms.URLField(label=_("URL"), required=False)
    # Translators: 'Comment' is a noun here.
    comment = forms.CharField(label=_('Comment'), widget=forms.Textarea,
                              max_length=COMMENT_MAX_LENGTH)

    def get_comment_object(self, site_id=None):
        """
        Return a new (unsaved) comment object based on the information in this
        form. Assumes that the form is already validated and will throw a
        ValueError if not.

        Does not set any of the fields that would come from a Request object
        (i.e. ``user`` or ``ip_address``).
        """
        if not self.is_valid():
            raise ValueError("get_comment_object may only be called on valid forms")

        CommentModel = self.get_comment_model()
        new = CommentModel(**self.get_comment_create_data(site_id=site_id))
        new = self.check_for_duplicate_comment(new)

        return new

    def get_comment_model(self):
        """
        Get the comment model to create with this form. Subclasses in custom
        comment apps should override this, get_comment_create_data, and perhaps
        check_for_duplicate_comment to provide custom comment models.
        """
        return get_model()

    def get_comment_create_data(self, site_id=None):
        """
        Returns the dict of data to be used to create a comment. Subclasses in
        custom comment apps that override get_comment_model can override this
        method to add extra fields onto a custom comment model.
        """
        return dict(
            content_type=ContentType.objects.get_for_model(self.target_object),
            object_pk=force_text(self.target_object._get_pk_val()),
            user_name=self.cleaned_data["name"],
            user_email=self.cleaned_data["email"],
            user_url=self.cleaned_data["url"],
            comment=self.cleaned_data["comment"],
            submit_date=timezone.now(),
            site_id=site_id or getattr(settings, "SITE_ID", None),
            is_public=True,
            is_removed=False,
        )

    def check_for_duplicate_comment(self, new):
        """
        Check that a submitted comment isn't a duplicate. This might be caused
        by someone posting a comment twice. If it is a dup, silently return the *previous* comment.
        """
        possible_duplicates = self.get_comment_model()._default_manager.using(
            self.target_object._state.db
        ).filter(
            content_type=new.content_type,
            object_pk=new.object_pk,
            user_name=new.user_name,
            user_email=new.user_email,
            user_url=new.user_url,
        )
        for old in possible_duplicates:
            if old.submit_date.date() == new.submit_date.date() and old.comment == new.comment:
                return old

        return new

    def clean_comment(self):
        """
        If COMMENTS_ALLOW_PROFANITIES is False, check that the comment doesn't
        contain anything in PROFANITIES_LIST.
        """
        comment = self.cleaned_data["comment"]
        if (not getattr(settings, 'COMMENTS_ALLOW_PROFANITIES', False) and
                getattr(settings, 'PROFANITIES_LIST', False)):
            bad_words = [w for w in settings.PROFANITIES_LIST if w in comment.lower()]
            if bad_words:
                raise forms.ValidationError(ungettext(
                    "Watch your mouth! The word %s is not allowed here.",
                    "Watch your mouth! The words %s are not allowed here.",
                    len(bad_words)) % get_text_list(
                    ['"%s%s%s"' % (i[0], '-' * (len(i) - 2), i[-1])
                     for i in bad_words], ugettext('and')))
        return comment


class CommentForm(CommentDetailsForm):
    honeypot = forms.CharField(required=False,
                               label=_('If you enter anything in this field '
                                       'your comment will be treated as spam'))

    def clean_honeypot(self):
        """Check that nothing's been entered into the honeypot."""
        value = self.cleaned_data["honeypot"]
        if value:
            raise forms.ValidationError(self.fields["honeypot"].label)
        return value

User/templates/User/change_password.html
{% extends 'product/base.html' %}
{% load staticfiles %}
<!-- The block below overwrites block in base -->
{% block head %}
    <title>تغییر رمزعبور</title>
{% endblock %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'User/change-password.css' %}"/>
{% endblock %}
{% block body %}
<div class="change-password">
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <p>
                <label for="id_old_password">پسورد قبلی:</label>
                <input id="id_old_password" name="old_password" autofocus="" required="" type="password">
            </p>

             <p>
                <label for="id_new_password1">پسورد جدید:</label>
                <input id="id_new_password1" name="new_password1" autofocus="" required="" type="password">
            </p>
            <p>
                <label for="id_new_password2">تکرار پسورد جدید:</label>
                <input id="id_new_password2" name="new_password2" autofocus="" required="" type="password">
            </p>

<ul>

    <li><p>پسورد شما نباید شبیه هیچکدام از اطلاعات شخصی شما باشد.</p></li>
    <li> <p>پسورد شما نمیتواند پسوردی باشد که قبلا استفاده شده.</p></li>
    <li><p>پسورد شما باید حداقل 8 حرفی باشد. </p></li>
    <li><p>پسورد شما نباید کاملا عددی باشد.</p> </li>
</ul>
            <button type="submit">تایید</button>
        </form>
        <br>
    </div>
</div>

{% endblock %}

User/templates/User/edit_profile.html
{% extends 'product/base.html' %}
{% load staticfiles %}
{% load tz %}
<!-- The block below overwrites block in base -->
{% block head %}
<title>Profile</title>
{% endblock %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'User/edit-profile.css' %}"/>
{% endblock %}
{% block body %}

<div class="container">

{% if error %}
<div class="alert alert-danger">
    <p><strong>خطا:</strong>{{ error }}</p>
</div>
{% endif %}

    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        <div class="edit-text-block">
        <table >

            <tr>
                <td style="">
                     <label for="city_id">شهر :</label>
                    <input id="city_id" name="city" type="text">

                </td>


            </tr>
            <tr>
                <td style="">
                    <label for="website_id">وبسایت :</label>
                    <input id="website_id" name="website" type="text">


                </td>

            </tr>
             <tr>
                <td style="">
                     <label for="phone_number_id">شماره تلفن :</label>
                    <input id="phone_number_id" name="phone_number" type="text" value="{{user.userprofile.phone_number}}">


                </td>
            </tr>
        </table>
        </div>
              <div class="edit-images-block">
        <table >
            <tr>
                <td>
                    <p>تصویر حساب:</p>

                    {% if user.userprofile.pro_img %}
<img style="height:200px;width:200px;" src="{{ user.userprofile.pro_img.url }}">

{% else  %}
<img style="height:200px;width:200px;" src="http://arminyahya.pythonanywhere.com/media/uploaded/default_img_prof.jpg">
{% endif %}
<br>
                    <label for="pro_img-clear_id">حذف عکس</label>
                    <input id="pro_img-clear_id" name="pro_img-clear" type="checkbox">
                </td>
            </tr>
            <tr>
                <td>
                    انتخاب عکس:
                    <input id="id_pro_img" name="pro_img" type="file">


                </td>

            </tr>
            <tr>
                {% get_current_timezone as TIME_ZONE %}
                <td><label for="timezone">منطقه زمانی:</label>
    <select name="timezone">
        {% for tz in timezones %}
        <option value="{{ tz }}" {% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
        {% endfor %}
    </select>
                </td>
            </tr>
            <tr><td>
                <input type="submit" value="تایید">
            </td></tr>
        </table>
              </div>
    </form>
    <br>
</div>

{% endblock %}

User/templates/User/login.html
{% extends 'product/base.html' %}
{% load staticfiles %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'User/login.css' %}"/>
{% endblock %}
{% block title %}
<title>ورود</title>
{% endblock %}

{% block body %}
<div class="container">
    <h2>خوش آمدید</h2>

    <h3>ورود:</h3>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
        <p>
                <label for="id_username">نام کاربری</label>
                <input class="form-control" id="id_username" name="username" autofocus="" required="" type="text">
            </p>
        <p>
                <label for="id_password">رمز عبور</label>
                <input class="form-control" id="id_password" name="password" autofocus="" required="" type="password">
            </p>
        <button type="submit">ورود</button>
        </div>
    </form>
&nbsp;
<div id="reg-paragraph">
    <p> اگر تا الان ثبت نام نکرده اید بر روی  <a href="/user/register">ثبت نام &nbsp;</a>کلیک کنید</p>
</div>
</div>
{% endblock %}

User/templates/User/logout.html
{% extends 'product/base.html' %}


{% block body %}
    <div class="container">
        <h2>شما خارج شدید</h2>

    </div>

{% endblock %}

User/templates/User/profile.html
{% extends 'product/base.html' %}
{% load tz %}
{% load staticfiles %}



{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'User/profile.css' %}"/>{% endblock %}

<!-- The block below overwrites block in base -->
{% block title %}
<title>profile</title>
{% endblock %}

{% block profile  %}

{% endblock %}

{% block body %}


<h3>پروفایل</h3>
<br>
{% if user.userprofile.pro_img %}
<img src="{{ user.userprofile.pro_img.url }}">

{% else  %}
<img src="http://arminyahya.pythonanywhere.com/media/uploaded/default_img_prof.jpg">
{% endif %}
<p>نام کاربری: {{ user }}</p>
<p>نام: {{ user.first_name }}</p>
<p>نام خانوادگی: {{ user.last_name }}</p>
<p>ایمیل: {{ user.email }}</p>
<p>شهر: {{ user.userprofile.city }}</p>
<p>شماره تلفن: {{ user.userprofile.phone_number }}</p>
<p>سایت: {{ user.userprofile.website }}</p>
{% get_current_timezone as TIME_ZONE %}
{% for tz in timezones %}
{% if tz == TIME_ZONE %}
<p>
    منطقه زمانی:{{tz}}
</p>
{% endif %}
 {% endfor %}
سبد خرید:

{% for item in items %}

<p>{{ item.product_name }}</p>
<a href="{% url 'product:change_item' operation='remove' pk=item.pk %}">
    <button class="btn btn-danger" type="submit"> حذف از سبد خرید</button>
</a>
{% empty %}
<p>سبد شما خالی است</p>

{% endfor %}
{% endblock %}

User/templates/User/reg_form.html
{% extends 'product/base.html' %}

{% load staticfiles %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'User/reg-form.css' %}"/>
{% endblock %}
{% block title %}
<title>فرم ثبت نام</title>
{% endblock %}

{% block body %}
<div class="container">

    {% if not user.is_authenticate %}

    <h2>ثبت نام</h2>
     {% if form1.non_field_errors or form2.non_field_errors %}
    <div class="alert alert-danger">
        {% if form1.non_field_errors %}

        {{ form1.non_field_errors}}
    {% else %}
        {{ form2.non_field_errors}}
    {% endif %}
    </div>
    {% else %}
    {% if form1.errors or form2.errors %}
    <div class="alert alert-danger">

        {% if form1.username.errors %}
        <p>{{ form1.username.errors }} </p>
        {% endif %}
        {% if form1.email.errors %}
        <p>{{ form1.email.errors }} </p>
        {% endif %}
        {% if form1.password1.errors %}
        <p>{{ form1.password1.errors }} </p>
        {% endif %}

        {% if form2.phone_number.errors %}
        <p>{{ form2.phone_number.errors }} </p>
        {% endif %}
        {% endif %}
        {% endif %}



    </div>
<div class="registration">
    <form method="post" novalidate>
        {% csrf_token %}
<div class="form-group">
       <p>
                <label for="id_username">نام کاربری</label>
                <input class="form-control" id="id_username" name="username" autofocus="" required="" type="text">
            </p>
   <p>
                <label for="first_name">نام </label>
                <input class="form-control" id="first_name" name="first_name" autofocus="" required="" type="text">
            </p>
    <p>
                <label for="last_name">نام خانوادگی</label>
                <input class="form-control" id="last_name" name="last_name" autofocus="" required="" type="text">
            </p>
    <p>
        <p>
                <label for="email">ایمیل</label>
                <input class="form-control" id="email" name="email" autofocus="" required="" type="email">
            </p>
     <p>
                <label for="phone_number">شماره تلفن همراه</label>
                <input class="form-control" id="phone_number" name="phone_number" autofocus="" required="" type="text">
            </p>
    <p>
                <label for="password1">رمز عبور</label>
                <input class="form-control" id="password1" name="password1" autofocus="" required="" type="password">
            </p>
    <ul>

    <li>پسورد شما نباید شبیه هیچکدام از اطلاعات شخصی شما باشد.</li>
    <li>پسورد شما نمیتواند پسوردی باشد که قبلا استفاده شده. </li>
    <li>پسورد شما باید حداقل 8 حرفی باشد. </li>
    <li>پسورد شما نباید کاملا عددی باشد. </li>
</ul>

    <p>
                <label for="password2">تکرار رمز</label>
                <input class="form-control" id="password2" name="password2" autofocus="" required="" type="password">
            </p>



</div>
         <button type="submit">تایید</button>
    </form>


{% else %}
    <p>  شما قبلا ثبت نام شده اید .برای مشاهده حساب کاربری خود  بر روی لینک زیر کلیک کنید</p>
    <a href="{% url 'user:view_profile' %}">حساب کاربری</a>
{% endif %}

</div>
</div>
 {% endblock %}

User/templates/User/reset_password.html
{% extends 'product/base.html' %}

{% block body %}
<div class="container">

    <div class="alert alert-info">
    <p><strong>توجه!!</strong>این قسمت فقط برای تست developer قرار داده شده است .</p>
</div>
    <h2>تغییر پسورد</h2>
    <p>
        اگر پسورد خود را فراموش کرده اید ایمیل خورد را در قسمت زیر وارد کنید.
    </p>

    <form method="post">
        {% csrf_token %}
       <p>
                <label for="id_email">ایمیل</label>
                <input id="id_email" name="email" autofocus="" required="" type="email">
            </p>
        <button type="submit">تایید</button>
    </form>
</div>
{% endblock %}

User/templates/User/reset_password_complete.html
{% extends 'product/base.html' %}

{% block body %}
    <div class="container">
        <h2>انجام شد</h2>
        <p>
            عملیات با موفقیت انجام شد
        </p>
    <a href="{% url 'user:login' %}">ورود
<button type="button">

    </button>
        </a>

        </div>
{% endblock %}

User/templates/User/reset_password_confirm.html
{% extends 'product/base.html' %}

{% block body %}
<div class="container">
    <h2>Enter new password</h2>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
       <p>
                <label for="id_new_password1">پسورد جدید</label>
                <input id="id_new_password1" name="new_password1" autofocus="" required="" type="password">
            </p>
            <p>
                <label for="id_new_password2">تکرار پسورد جدید</label>
                <input id="id_new_password2" name="new_password2" autofocus="" required="" type="password">
            </p>

<ul>

    <li>پسورد شما نباید شبیه هیچکدام از اطلاعات شخصی شما باشد.</li>
    <li>پسورد شما نمیتواند پسوردی باشد که قبلا استفاده شده. </li>
    <li>پسورد شما باید حداقل 8 حرفی باشد. </li>
    <li>پسورد شما نباید کاملا عددی باشد. </li>
</ul>
        <button type="submit">تایید</button>
    </form>
</div>
{% endblock %}

User/templates/User/reset_password_done.html
{% extends 'product/base.html' %}

{% block body %}
    <div class="container">

    <p>
        برای شما ایمیلی ارسال شده است که حاوی یک دستورالعمل است.


    </p>
    </div>
{% endblock %}

User/templates/User/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
{% trans "Please go to the following page and choose a new password:" %}

{{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}

{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
{% trans "Thanks for using our site!" %}
{% blocktrans %}The {{ site_name }} team {% endblocktrans %}
{% endautoescape %}