User/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

import product
from . import views
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import password_reset
from django.contrib.auth.views import password_reset_done
from django.contrib.auth.views import password_reset_confirm
from django.contrib.auth.views import password_reset_complete

from product import views as PV

app_name = 'user'
urlpatterns = [
    url(r'^$', PV.Home.as_view()),
    url(r'^upload-file/$', TemplateView.as_view(template_name= 'User/upload.html')),

    # Allows to render our own login page
    url(r'^login/$', login, {'template_name': 'User/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'User/logout.html'}),
    url(r'register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', password_reset, {'template_name': 'User/reset_password.html',
                                               'post_reset_redirect': 'user:password_reset_done',
                                               'email_template_name': 'User/reset_password_email.html'},
        name='reset_password'),
    url(r'^rezome/$', TemplateView.as_view(template_name='User/rezome.html'), name='rules'),

    url(r'^reset-password-done$', password_reset_done, {'template_name': 'User/reset_password_done.html'},
        name='password_reset_done'),
    # url(r'^reset-password/confirm$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'User/reset_password_confirm.html',
         'post_reset_redirect': 'user:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^reset-password/complete$', password_reset_complete,
        {'template_name': 'User/reset_password_complete.html'}, name='password_reset_complete'),

]

# url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
#     name='password_reset_confirm')

# python -m smtpd -n -c DebuggingServer localhost:1025
# and adjust your mail settings accordingly:
# EMAIL_HOST = 'localhost'
# EMAIL_PORT = 1025

product/api/urls.py
from django.conf.urls import url
from .views import (PostListApiView,
                    PostDetailApiView,
                    PostDestroyApiView,
                    PostUpdateApiView,
                    CommentDetailApiView, CommentDestroyApiView, CommentUpdateApiView, CommentListApiView)

# namespace


urlpatterns = [

    url(r'^$', PostListApiView.as_view(), name='PostListApi'),
    url(r'^detail/(?P<product_name>(\w+\s*\w+))/$', PostDetailApiView.as_view(), name='post-detail'),
    url(r'^detail/(?P<product_name>\w+)/delete/$', PostDestroyApiView.as_view(), name='post-delete'),
    url(r'^detail/(?P<product_name>\w+)/edit/$', PostUpdateApiView.as_view(), name='post-update'),

    url(r'^comments/$', CommentListApiView.as_view(), name='CommentListApi'),
    url(r'^comments/(?P<pk>\w+)/$', CommentDetailApiView.as_view(), name='comment-detail'),
    url(r'^comments/(?P<pk>\w+)/delete/$', CommentDestroyApiView.as_view(), name='comment-delete'),
    url(r'^comments/(?P<pk>\w+)/edit/$', CommentUpdateApiView.as_view(), name='comment-update'),

]

product/urls.py
from django.conf.urls import url, include
from .views import Home, change_items,set_timezone
from .views import detail, category

# namespace
app_name = 'product'

urlpatterns = [

    url(r'^$', Home.as_view(), name='home'),
    url(r'^product/(?P<operation>.+)/(?P<pk>\d+)/$', change_items, name='change_item'),
    url(r'^detail/(?P<pk>\d+)/$', detail, name='detail'),
    url(r'^product/(?P<product_category>.+)/$', category, name='category'),

]

shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import refresh_jwt_token
from rest_framework_jwt.views import verify_jwt_token
from product.views import contact, about_us, advertising, set_timezone,Search
from shop import settings

urlpatterns = [

    url(r'^admin/', admin.site.urls),

    url(r'', include('product.urls')),
    url(r'^user/', include('User.urls')),
   # url(r'^search/', include('haystack.urls')),
    url(r'^search/', Search,name='search'),

    url(r'^contact/$', contact, name='Contact'),
    url(r'^about-us/$', about_us, name='about-us'),
    url(r'^advertising/$', advertising, name='advertising'),
    url(r'^timezone/$', set_timezone, name='timezone'),
    url(r'^api/posts/', include('product.api.urls', namespace='api-posts')),
    url(r'^api/users/', include('User.api.urls', namespace='api-users')),

    url(r'^auth-jwt/', obtain_jwt_token),
    url(r'^auth-jwt-refresh/', refresh_jwt_token),
    url(r'^auth-jwt-verify/', verify_jwt_token),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
]

User/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User

from django.db import models


class UserProfile(models.Model):
    # Each user-field in UserProfile can only have one user
    user = models.ForeignKey(User, related_name="userprofile", null=True)
    phone_number = models.CharField(max_length=11, blank=True)

    city = models.CharField(max_length=100, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    pro_img = models.FileField(null=True, blank=True, upload_to='uploaded')

    def __str__(self):
        if self.user:
            return self.user.username
        return "unknown"

    @classmethod
    def create_profile(cls, user, phone_number):
        userprofile = cls.objects.create(

            user=user
        )
        userprofile.phone_number = phone_number
        userprofile.save()


"""
Note: Receiver of UsersMessage and GuestMessage is admin  cuz we don't need chat between users in a shop 

"""


# Here is Contact for Guest that i said before
class UsersMessage(models.Model):
    author = models.OneToOneField(User, related_name="author", null=True, blank=True)

    cooperate = 'co'
    problem_buying = 'pb'
    ask_game = 'ag'
    others = 'o'

    options = ((cooperate, 'همکاری'), (problem_buying, 'مشکل در خرید'), (ask_game, 'درخواست بازی'), (others, 'موارد دیگر'))
    issue_options = models.CharField(choices=options, default=cooperate, max_length=2)
    message = models.TextField(max_length=250, null=True)

    def __str__(self):
        return str(self.author) + " " + str(self.issue_options)


# Here is Contact for Guest that i said before
class GuestMessage(models.Model):
    Guest_first_name = models.CharField(max_length=10, null=True)
    Guest_last_name = models.CharField(max_length=10, null=True)
    Guest_email = models.EmailField(max_length=50, null=True)
    cooperate = 'co'
    problem_buying = 'pb'
    ask_game = 'ag'
    others = 'o'

    options = (
        (cooperate, 'همکاری'), (problem_buying, 'مشکل در خرید'), (ask_game, 'درخواست بازی'), (others, 'موارد دیگر'))
    issue_options = models.CharField(choices=options, default=cooperate, max_length=2)
    message = models.TextField(max_length=250, null=True)

    def __str__(self):
        return str(self.Guest_first_name) + " " + str(self.issue_options)

product/models.py
from django.contrib.auth.models import User
from django.db import models


# Create Posts Models for Product which we want to add in our site
class Post(models.Model):
    product_name = models.CharField(max_length=250)

    product_prize = models.CharField(max_length=250)

    product_img = models.FileField(null=True, blank=True, upload_to='uploaded')

    product_des = models.TextField(max_length=2000)

    product_category = models.CharField(max_length=250)

    class Meta:
        ordering = ['product_name']

    def __str__(self):
        return self.product_name


# Each User have a Basket for buying the Products
class Basket(models.Model):
    product_name = models.ManyToManyField(Post,)

    current_user = models.ForeignKey(User, related_name='basket')

    @classmethod
    def add_item(cls, current_user, new_item):
        # We check our user already have a basket or not, if not we create one for him

        basket, create = cls.objects.get_or_create(

            current_user=current_user
        )

        basket.product_name.add(new_item)

    @classmethod
    def remove_item(cls, current_user, new_item):
        basket, created = cls.objects.get_or_create(

            current_user=current_user
        )

        basket.product_name.remove(new_item)


class CommentManager(models.Manager):
    def all(self):
        qs = super(CommentManager, self).filter(parent=None)

        return qs


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    user = models.ForeignKey(User, null=True)
    body = models.TextField(max_length=250, null=True)
    created = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    parent = models.ForeignKey("self", null=True, blank=True)
    public = models.BooleanField(default=False)

    def approved(self):
        self.approved = True
        self.save()

    def __str__(self):

        return self.user.username

    def is_parent(self):
        if self.parent is not None:
            return False
        return True

    # is_public for moderation
    def is_public(self):

        if self.public:
            return True
        return False

    def children(self):
        return Comment.objects.filter(parent=self)

class FileUpload(models.Model):

    img = models.FileField(null=True,upload_to='uploaded')

product/api/views.py
from django.db.models import Q
from rest_framework import request
from rest_framework.generics import \
    (ListAPIView,
     RetrieveAPIView,
     UpdateAPIView,
     DestroyAPIView,
     RetrieveUpdateAPIView,
     )

from rest_framework.permissions import \
    (AllowAny,
     IsAdminUser,
     IsAuthenticated,
     IsAuthenticatedOrReadOnly)
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.pagination import LimitOffsetPagination, PageNumberPagination

from product.api.pagination import PostLimitOffsetPagination
from product.api.serializer import PostListSerializer, CommentListSerializer, PostDetailSerializer, \
    CommentDetailSerializer
from product.models import Post, Comment
from .permissions import IsOwnerOrReadOnly


class PostDetailApiView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer

    lookup_field = 'product_name'


class PostListApiView(ListAPIView):
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]#?search=...&ordering=
    pagination_class = PostLimitOffsetPagination
    search_fields = ['product_name','product_prize']
    ordering = ('-product_prize',)

    def get_queryset(self, *args, **kwargs):
        queryset_list = Post.objects.all()
        query = self.request.GET.get("q")#?q=...
        if query:
            queryset_list = queryset_list.filter(
                Q(product_name__icontains=query) |
                Q(product_prize__icontains=query) |
                Q(product_category__icontains=query)
            ).distinct()

        return queryset_list


class PostUpdateApiView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostListSerializer
    permission_classes = [IsAdminUser]
    lookup_field = 'product_name'


class PostDestroyApiView(DestroyAPIView):
    queryset = Post.objects.all()
    permission_classes = [IsAdminUser]
    serializer_class = PostListSerializer
    lookup_field = 'product_name'


class CommentListApiView(ListAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentListSerializer



class CommentDetailApiView(RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentDetailSerializer


class CommentUpdateApiView(RetrieveUpdateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentListSerializer
    permission_classes = [IsOwnerOrReadOnly,IsAdminUser]


class CommentDestroyApiView(DestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentListSerializer

product/views.py
from django.db.models import Q
from django.shortcuts import render, redirect

from django.views.generic import ListView
import pytz

from User.form import ContactForm, UsersContactForm
from product.form import CommentForm
from .models import Post, Basket, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def set_timezone(request):
    if request.method == 'POST':
        request.session['django_timezone'] = request.POST['timezone']
        return redirect('/')
    else:
        return render(request, 'product/timezone.html', {'timezones': pytz.common_timezones})


class Home(ListView):
    # In this template we show all posts.
    model = Post
    template_name = 'product/posts.html'
    context_object_name = 'posts'
    #  pagination more detail www.simplebetterthancomplex.com
    paginate_by = 6
    queryset = Post.objects.all()


def category(request, product_category):
    posts_list = Post.objects.filter(product_category=product_category)

    paginator = Paginator(posts_list, 6)
    template_name = 'product/results.html'
    page = request.GET.get('page', 1)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {'posts': posts, 'category': product_category}
    return render(request, template_name, context)


"""
Here we have two Contact one for Users and another for Guests with two different form and two different template
"""


def contact(request):
    users_template_name = 'product/UsersContact.html'
    guest_template_name = 'product/GuestContact.html'
    if request.method == 'POST':

        if request.user.is_authenticated:

            form = UsersContactForm(request.POST)
            if form.is_valid():
                # use print for debugging
                print('valid-users-form')
                usermassage = form.save(commit=False)
                usermassage.author = request.user
                form.save(commit=True)
                return redirect('product:home')
            else:
                print('invalid-users-form')

                print('authenticated')
                form = UsersContactForm()
                return render(request, users_template_name, {'form': form})
        else:
            form = ContactForm(request.POST)
            if form.is_valid():
                print('guest-valid')
                form.save()
                return redirect('product:home')
            else:
                print('guest-invalid')

                form = ContactForm()
                return render(request, guest_template_name, {'form': form})

    else:
        if request.user.is_authenticated:

            print('authenticated')
            form = UsersContactForm()
            return render(request, users_template_name, {'form': form})
        else:

            form = ContactForm()
            return render(request, guest_template_name, {'form': form})


def about_us(request):
    template_name = 'product/about-us.html'
    return render(request, template_name)


def advertising(request):
    template_name = 'product/advertising.html'
    return render(request, template_name)


# Maybe our Users want to change their basket of games
def change_items(request, operation, pk):
    new_item = Post.objects.get(pk=pk)

    if operation == 'add':
        Basket.add_item(request.user, new_item)

    if operation == 'remove':
        Basket.remove_item(request.user, new_item)

    return redirect('product:home')


# Each product most have extra information
def detail(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            try:
                parent_id = int(request.POST.get("parent_id"))

            except:
                parent_id = None
                print("error")

            if parent_id:
                comment.parent = Comment.objects.get(pk=parent_id)

            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect('product:detail', pk=post.pk)
    else:
        form = CommentForm()
    template_name = 'product/details.html'
    context = {'form': form, 'post': post}
    return render(request, template_name, context)


def Search(request):
    template_name = 'product/search.html'
    queryset_list = None
    query = request.GET.get('q')

    if query:
        queryset_list = Post.objects.all().filter(
            Q(product_name__icontains=query) |
            Q(product_prize__icontains=query) |
            Q(product_category__icontains=query)
        )
    context = {'queryset_list': queryset_list}
    return render(request,template_name,context)

product/templates/product/Advertising.html
{% extends 'product/base.html' %}
{% block title %}
<title>تبلیغات</title>
{% endblock %}

{% block body %}
<p>باید به اطلاع برسانم که قیمت تبلیغات درسایت هنوز مشخص نیست واین قیمت توسط خریدار سایت مشخص میشود.  </p>
{% endblock %}

product/templates/product/GuestContact.html
{% extends 'product/base.html'%}
{% load staticfiles %}


{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'product/GuestContact.css' %}"/>
{% endblock %}

{% block title %}
<title> &nbsp;&nbsp; تماس با ما </title>
{% endblock %}
{% block body %}
<h2>تماس با ما </h2>

<form method="POST">
    {% csrf_token %}
    <div class="form-group">
<label for="id_Guest_first_name" > نام  </label>
    <input class="form-control" id="id_Guest_first_name" name="Guest_first_name" maxlength="10" required="" type="text">
        </div>
      <div class="form-group">
<label for="id_Guest_last_name" >نام خانوادگی</label>
    <input class="form-control" id="id_Guest_last_name" name="Guest_last_name" maxlength="10" required="" type="text">
        </div>
      <div class="form-group">
<label for="id_Guest_email">ایمیل</label>
    <input class="form-control" id="id_Guest_email" name="Guest_email" maxlength="50" required="" type="email">
        </div>
    <div class="form-group">
        <label for="id_issue_options">دسته بندی</label>
        <select class="form-control" id="id_issue_options" name="issue_options">
            <option value="co" selected="">
    همکاری
            </option>
            <option value="pb">
مشکل در خرید
            </option >
            <option value="ag">
درخواست بازی
            </option>
            <option value="o">
موارد دیگر
            </option>

        </select>


    </div>

           <div class="form-group">
  <label for="id_message">پیام</label>
    <textarea  class="form-control" id="id_message" name="message" cols="5" rows="4" maxlength="250" required="">
    </textarea>
</div>



    <input type="submit" value="Submit">




</form>

{% endblock %}

product/templates/product/Roles.html
{% extends 'product/base.html' %}
{% load staticfiles %}
{% block title %}
<title>قوانین سایت</title>
{% endblock %}

{% block body %}

{% endblock %}

product/templates/product/UsersContact.html
{% extends 'product/base.html'%}
{% load staticfiles %}


{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'product/UsersContact.css' %}"/>
{% endblock %}

{% block title %}
<title> &nbsp;&nbsp; تماس با ما </title>
{% endblock %}
{% block body %}

<h2>تماس با ما </h2>
<form method="POST">
    {% csrf_token %}

    <div class="form-group">

        <label for="id_issue_options" >دسته بندی</label>
        <select class="form-control" id="id_issue_options" name="issue_options" >
            <option value="co" selected="">
                همکاری
            </option>
            <option value="pb">
                مشکل در خرید
            </option>
            <option value="ag">
                درخواست بازی
            </option>
            <option value="o">
                موارد دیگر
            </option>

        </select>

    </div>

    <div class="form-group">
        <label for="id_message">پیام</label>
        <textarea class="form-control" id="id_message" name="message"  rows="4"  maxlength="250" required="">
    </textarea>
        <input type="submit" value="ارسال">
    </div>



</form>

{% endblock %}

product/templates/product/about-us.html
{% extends 'product/base.html' %}


{% load staticfiles %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'product/about-us.css' %}"/>
{% endblock %}
{% block title %}
<title>درباره ما </title>
{% endblock %}

{% block body %}
<p style="color:black;">این فروشگاه  با هدف ارائه محصولات دیجیتال اورجینال و
    اصلی و ترویج فرهنگ احترام به قانون کپی رایت شروع به کار کرده است.
    این فروشگاه لایسنس ( CDKEY ) بازی های ویدئویی تحت DRM های
    مختلف را به خریداران محترم به وسیله ی ایمیل ارسال مینماید
و هیچکدام از محصولات فروشگاه به صورت فیزیکی نمیباشد. </p>
{% endblock %}

product/templates/product/add_comment.html
{% extends 'product/base.html' %}


{% block body %}
<form method="POST">{% csrf_token %}
    {{form.as_p}}
    <button type="submit" value="addcomment"></button>
</form>
{% endblock %}

product/templates/product/add_comment_to_post.html
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>

product/templates/product/base.html
<!DOCTYPE html>
<html dir="rtl" lang="fa-IR">
<head>
    <!-- Use boostrap and css file stored in product/base.css -->

    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


    <link rel="stylesheet" type="text/css" href="{% static 'product/base.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    {% block style %}
    <!--  another pages which inherited from base.html can add their own style file to page !!!  -->
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="{% static 'product/css/emoji.css'%}" rel="stylesheet">
    {% block title %}
    <title>base</title>
    {% endblock %}
</head>

<body>

<!-- In base.html we focus on nav-bar ,background, container  -->

<div class="container" id="top-side">

    <div class="jumbotron">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'product:home' %}">GameShop</a>
                </div>
                <div class="collapse navbar-collapse">

                    <ul class="nav navbar-nav" id="left-side">
                        <li><a href="/contact/">تماس با ما </a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">دسته بندی <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'product:category' product_category='steam' %} ">Steam</a>

                                </li>

                                <li>
                                    <a href="{% url 'product:category' product_category='origin' %} ">Origin</a>

                                </li>
                                <li>
                                    <a href="{% url 'product:category' product_category='battle.net' %} ">Battle.net </a>
                                </li>
                            </ul>
                        </li>
                    </ul>


                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">
                                {% if user.userprofile.pro_img %}
                                <img class="nav-prof-img" src="{{ user.userprofile.pro_img.url}}">

                                {% else %}
                                <img class="nav-prof-img"
                                     src="http://arminyahya.pythonanywhere.com/media/uploaded/default_img_prof.jpg">
                                {% endif %}

                            </a>

                            <ul class="dropdown-menu">
                                {% if user.is_authenticated %}
                                <li style=""><a href="/user/profile"><span
                                        class="glyphicon glyphicon-user"
                                        aria-hidden="true"></span>حساب کاربری</a></li>
                                <li><a href="/user/logout"><span
                                        class="glyphicon glyphicon-log-out"
                                        aria-hidden="true"></span> خروج</a></li>

                                <li class="dropdown-header">ویرایش حساب</li>
                                <li><a href="/user/profile/edit">ویرایش پروفایل</a></li>
                                <li><a href="/user/change-password">عوض کردن پسورد</a></li>
                                <li><a href="/user/reset-password">عوض کردن پسورد
                                    باایمیل</a></li>
                                {% else %}
                                <li><a href="/user/login"><span
                                        class="glyphicon glyphicon-log-in"
                                        aria-hidden="true"></span> ورود</a></li>
                                {% endif %}
                            </ul>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>

        <div class="search-panel">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form method="get" action="/search/">
                        <table>

                            <tr>

                                <td>

                                    <input name="q" type="search" placeholder="جستجو در سایت">


                                </td>
                                <td>
                                    <button type="submit" class="btn btn-xs">
                                        <span>جستجو</span>
                                    </button>
                                </td>
                            </tr>
                        </table>
                    </form>

                </div>
            </div>


        </div>


        {% block body %}
        {% endblock %}



    </div>
</div>
<div class="panel-footer navbar-inverse ">
    <div class="post">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-4" id="footer-right-side" style="">

                <ul>
                    <li>

                        <a href="http://www.metacritic.com/game.com">مشاهده نمرات بازی ها </a>
                        <hr>
                    </li>


                    <li>
                        <a href="/advertising/"> تبلیغات </a>
                        <hr>

                    </li>

                    <li>

                        <a href="/about-us/"> درباره ما </a>
                        <hr>
                    </li>

                    <li>


                        <a>ایمیل:armin_yahya@yahoo.com</a>

                    </li>

                </ul>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-4" id="footer-copy-right">
                <p>© هرگونه کپی‌برداری از محتواهای این سایت ممنوع و غیر مجاز است.</p>
                <p> backendوfrontend این سایت توسط آرمین یحیی ساخته شده است. </p>

            </div>


            <div class="col-xs-12 col-sm-12 col-md-4" style="" id="footer-media">
                <p style="">ما را در شبکه های اجتماعی دنبال کنید</p>

                <a href="https:/www.telegram.com/"><img src="{% static 'product/telegram.png' %}" style=""></a>
                <a href="https://plus.google.com/"><img src="{% static 'product/google.png' %}" style=""></a>
                <a href="https://instagram.com/"><img src="{% static 'product/instagram.png' %}" style=""></a>


            </div>


        </div>
    </div>
</div>
<script>
$(document).ready(function(){
  $('.gr_ver_2').css({
    'top': 'auto'
  });
})
</script>
</body>

</html>

product/templates/product/form.html
{% get_comment_form for entry as form %}
<!-- A context variable called form is created with the necessary hidden
fields, timestamps and security hashes -->

 <form action="{% url 'product:home' %}" method="post">
    {% csrf_token %}
    {{ form }}



        <input type="submit" name="submit" value="Post">
        <input type="submit" name="preview" value="Preview">

  </form>

product/templates/product/results.html
{% extends 'product/posts.html' %}

{% load staticfiles %}
{% block title %}
<title>{{ category }} games</title>
{% endblock %}

{% block pagination %}

{% if posts.has_other_pages %}
<div class="text-center">
    <ul class="pagination">
        {% if posts.has_previous %}
        <li><a href="?page={{ posts.previous_page_number }}"><span>&raquo;</span></a></li>
        {% else %}
        <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
        {% for i in posts.paginator.page_range %}
        {% if posts.number == i %}
        <li class="active"><span>{{ i }}</span></li>
        {% else %}
        <li><a href="?page={{ i }}"><span>{{ i }}</span></a></li>
        {% endif %}
        {% endfor %}
        {% if posts.has_next %}
        <li><a href="?page={{ posts.next_page_number }}"><span>&laquo;</span></a></li>
        {% else %}
        <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
    </ul>

</div>
  {% endif %}
{% endblock%}